CREATE TABLE ezpunishments_punishments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  reason TEXT NOT NULL,
  proof TEXT,
  punished_by TEXT NOT NULL,
  removed_by TEXT,
  active BOOLEAN NOT NULL,
  expires TIMESTAMP,
  date_punished TIMESTAMP NOT NULL DEFAULT now(),
  updated TIMESTAMP
);