CREATE TABLE ezpunishments_users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  email TEXT,
  user_name TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  date_created TIMESTAMP NOT NULL DEFAULT now(),
  date_modified TIMESTAMP
);