CREATE TABLE ezpunishments_reset_password (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER REFERENCES ezpunishments_users(id) ON DELETE CASCADE,
  token TEXT NOT NULL,
  expire TIMESTAMP NOT NULL,
  status INTEGER DEFAULT 0
);